# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
  - pipeline: deploy-to-prod # Name of the pipeline resource.
    source: 'Intellipaat-Maven-CI' # The name of the pipeline referenced by this pipeline resource.
    trigger:
      branches:
      - master
      
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
